vich_uploader:
    db_driver: orm

    mappings:
        produit_image:
            uri_prefix: /images/Produits/
            upload_destination: '%kernel.project_dir%/public//images/Produits/'
        
        ingredient_image:
            uri_prefix: /images/Ingredients/
            upload_destination: '%kernel.project_dir%/public//images/Ingredients/'

        categorie_image:
            uri_prefix: /images/Categories/
            upload_destination: '%kernel.project_dir%/public//images/Categories/'     
